use FireUp;
insert into houses (address,city,state,zipcode,description,house_id) values ('1114 Hermitage Street SE','Grand Rapids','MI','49506','Description',1);
insert into houses (address,city,state,zipcode,description,house_id) values ('629 Parkwood Street NE','Grand Rapids','MI','49503','Description',2);
insert into houses (address,city,state,zipcode,description,house_id) values ('56 Uniion Avenue NE','Grand Rapids','MI','49503','Description',3);
insert into photos (picid,format,house_id) values ('herm_din','jpg',1);
insert into photos (picid,format,house_id) values ('herm_ex_2','jpg',1);
insert into photos (picid,format,house_id) values ('herm_ex_3','jpg',1);
insert into photos (picid,format,house_id) values ('herm_ex','jpg',1);
insert into photos (picid,format,house_id) values ('herm_kitch','jpg',1);
insert into photos (picid,format,house_id) values ('herm_kitch_2','jpg',1);
insert into photos (picid,format,house_id) values ('herm_liv_room_2','jpg',1);
insert into photos (picid,format,house_id) values ('herm_liv_room','jpg',1);
insert into photos (picid,format,house_id) values ('herm','jpg',1);
insert into photos (picid,format,house_id) values ('park_1','jpg',2);
insert into photos (picid,format,house_id) values ('park_2','jpg',2);
insert into photos (picid,format,house_id) values ('park_3','jpg',2);
insert into photos (picid,format,house_id) values ('park_4','jpg',2);
insert into photos (picid,format,house_id) values ('park_5','jpg',2);
insert into photos (picid,format,house_id) values ('park_6','jpg',2);
insert into photos (picid,format,house_id) values ('park_7','jpg',2);
insert into photos (picid,format,house_id) values ('park_8','jpg',2);
insert into photos (picid,format,house_id) values ('park_9','jpg',2);
insert into photos (picid,format,house_id) values ('park_10','jpg',2);
insert into photos (picid,format,house_id) values ('park_11','jpg',2);
insert into photos (picid,format,house_id) values ('park_12','jpg',2);
insert into photos (picid,format,house_id) values ('union_1','jpg',3);
